## 使用mimic-cxr和rocov2两个数据集跑通baseline
data:
  batch_size: 4
  num_workers: 6
  return_pil: true
  pin_memory: true

  sources:
    

    - name: rocov2
      root: "/root/autodl-tmp"
      ann:
        train: "/root/autodl-tmp/rocov2/caption_rocov2_train.json"
        valid: "/root/autodl-tmp/rocov2/caption_rocov2_val.json"
        test:  "/root/autodl-tmp/rocov2/caption_rocov2_test.json"
      image_key: "image"
      text_key: "caption"
      id_key: "image_id"
