## 使用mimic-cxr和rocov2两个数据集跑通baseline
data:
  batch_size: 4
  num_workers: 6
  return_pil: true
  pin_memory: true

  sources:
    - name: mimic_cxr
      root: "/data"  # 与标注中的 image 相对路径拼接的根目录
      ann:
        train: "/data/mimic_cxr/train.json"
        valid: "/data/mimic_cxr/valid.json"
        test:  "/data/mimic_cxr/test.json"
      image_key: "image"
      text_key: "caption"
      id_key: null

    - name: rocov2
      root: "/data"
      ann:
        train: "/data/rocov2/train.json"
        valid: "/data/rocov2/valid.json"
        test:  "/data/rocov2/test.json"
      image_key: "image"
      text_key: "caption"
      id_key: "image_id"
